name: store_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  animated_bottom_navigation_bar: ^1.3.3
  gradient_elevated_button: ^0.0.5
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  get_storage: ^2.1.1
  animated_notch_bottom_bar: ^1.0.0
  flutter_animate: ^4.5.0
  lottie: ^2.7.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
    - assets/lotties/
  uses-material-design: true

